@startuml
interface org.newdawn.spaceinvaders.app.Screen {
~ void onShow()
~ void onHide()
~ void init()
~ void update(long)
~ void render(Graphics2D)
}

interface org.newdawn.spaceinvaders.app.ScreenNavigator {
~ void showLogin()
~ void showMainMenu()
~ void startNewGame()
~ void exitGame()
~ void setResolution(int,int)
~ int getCurrentWidth()
~ int getCurrentHeight()
~ ResolutionManager getResolutionManager()
~ void showRoomList(GameClient)
~ void showRoomLobby(String)
~ void startMultiplayerGame(GameClient,GameInitInfo)
}

@enduml