@startuml
class org.newdawn.spaceinvaders.gameplay.entity.SideMonster {
- Game game
- double moveSpeed
- boolean movingRight
- int currentHP
- int maxHP
- int round
- long lastIceAttack
- long iceAttackInterval
- {static} String getSideMonsterSpriteForRound(int)
+ void move(long)
- void checkBossCollision()
+ void draw(Graphics)
+ Rectangle getBounds()
+ void takeDamage(int)
+ int getCurrentHP()
+ int getMaxHP()
+ void tryIceAttack()
+ void collidedWith(Entity)
}


class org.newdawn.spaceinvaders.gameplay.ui.SharedHudRenderer {
- BufferedImage cachedHpImage
- BufferedImage cachedCoinImage
+ void drawHud(Graphics2D,HudContext)
- void drawRoundAndHp(Graphics2D,HudContext)
- void drawHpBar(Graphics2D,HudContext)
- void drawSkillStats(Graphics2D,HudContext)
- void drawSkillInventory(Graphics2D,HudContext)
- void drawSkillEffects(Graphics2D,HudContext)
- void drawPlayTimeAndCoins(Graphics2D,HudContext)
- void drawSkillIconSlot(Graphics2D,int,int,String,int,int,int)
- void drawSkillCount(Graphics2D,int,int,int)
- BufferedImage getHpImage()
- BufferedImage getCoinImage()
- BufferedImage loadSkillImage(int)
}


interface org.newdawn.spaceinvaders.gameplay.core.GameplayContext {
~ GameStateManager getGameStateManager()
~ SkillManager getSkillManager(String)
~ ShipEntity getShip(String)
~ ShipEntity createPlayerShip(String)
~ Entity createAlienEntity(int,int)
~ Entity createNearEntity(int,int)
~ Entity createBossEntity(int)
~ List<Entity> getActiveEntities()
~ List<Entity> getPendingRemovals()
~ void addEntity(Entity)
~ void removeEntity(Entity)
~ void createSkillDrop(int,int,int,int)
~ void fireMissile(String,double,double)
~ void onRoundBackgroundChanged(int)
~ void addEarnedCoins(String,int)
~ void showCoinEarned(String,int,int,int)
~ void onGameCompleted(String)
}

class org.newdawn.spaceinvaders.gameplay.entity.Skill {
- Game game
- boolean used
- int skillType
- int skillValue
- double moveSpeed
- BufferedImage skillIcon
+ void move(long)
+ void collidedWith(Entity)
+ int getSkillType()
+ int getSkillValue()
+ boolean isUsed()
- void loadSkillIcon()
+ void draw(Graphics)
}


class org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round4GreenSphereAttack {
- Game game
- int damage
- double moveSpeed
- long attackDuration
- long startTime
- int sphereSize
+ void move(long)
+ void draw(Graphics)
+ void collidedWith(Entity)
}


class org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round4PlayerLineAttack {
- Game game
- java.awt.Image attackImage
- long attackDuration
- long startTime
- int attackWidth
- int attackHeight
- int playerLineY
- void loadAttackImage()
+ void move(long)
+ void draw(Graphics)
+ void collidedWith(Entity)
}


interface org.newdawn.spaceinvaders.gameplay.ui.HudContext {
~ int getCurrentRound()
~ int getMaxRound()
~ int getCurrentHp()
~ int getMaxHp()
~ int getSkillPoints()
~ int getAttackPower()
~ double getAttackSpeed()
~ int getInvincibleSkillCount()
~ int getTripleShotSkillCount()
~ int getMissileSkillCount()
~ boolean isInvincibleActive()
~ long getInvincibleRemainingMs()
~ boolean isTripleShotActive()
~ long getTripleShotRemainingMs()
~ String getFormattedPlayTime()
~ int getEarnedCoins()
}

class org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round2RandomAttack {
- Game game
- double moveSpeed
- int damage
- Image attackImage
- double targetY
- long slashDuration
- long startTime
- void loadAttackImage()
+ void move(long)
+ void draw(Graphics)
+ void collidedWith(Entity)
}


class org.newdawn.spaceinvaders.gameplay.entity.entity_attack.IceAttack {
- Game game
- double moveSpeed
- int damage
- Image iceImage
- double scale
- void loadIceImage()
+ void move(long)
+ void draw(Graphics)
+ Rectangle getBounds()
+ void collidedWith(Entity)
}


class org.newdawn.spaceinvaders.gameplay.net.GameEvent {
+ Type type
+ String fromPlayerId
+ String message
+ long time
}

enum org.newdawn.spaceinvaders.gameplay.net.Type {
+  CHAT
+  SYSTEM
}

class org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round3PullAttack {
- Game game
- java.awt.Image attackImage
- double pullStrength
- long attackDuration
- long startTime
- int attackWidth
- int attackHeight
- double pullRange
- void loadAttackImage()
+ void move(long)
- void pullPlayer()
+ void draw(Graphics)
- void launchBlackHoleAttack()
+ void collidedWith(Entity)
}


class org.newdawn.spaceinvaders.gameplay.entity.entity_attack.MagneticFieldEntity {
- Game game
- double fieldRadius
- double fieldStrength
- long duration
- long startTime
- boolean isActive
- int pulsePhase
- double currentRadius
+ void move(long)
- void applyMagneticEffects()
- void applyForceToShip(Entity,double,double)
- void applyForceToShot(Entity,double,double)
- double getDistanceTo(Entity)
+ void draw(Graphics)
+ void collidedWith(Entity)
+ boolean isActive()
+ double getFieldRadius()
+ double getFieldStrength()
+ double getCurrentRadius()
}


class org.newdawn.spaceinvaders.gameplay.ResolutionManager {
+ {static} int BASE_WIDTH
+ {static} int BASE_HEIGHT
- int currentWidth
- int currentHeight
- double uniformScale
+ void setResolution(int,int)
+ double getScaleX()
+ double getScaleY()
+ double getUniformScale()
+ int getCurrentWidth()
+ int getCurrentHeight()
+ int scaleX(int)
+ int scaleY(int)
+ int uniformScale(int)
+ int unscaleX(int)
+ int unscaleY(int)
+ float scaleFontSize(float)
+ int scaleImageSize(int)
+ String toString()
}


class org.newdawn.spaceinvaders.gameplay.net.PlayerInput {
+ String playerId
+ boolean left
+ boolean right
+ boolean fire
+ long clientTime
}

class org.newdawn.spaceinvaders.gameplay.entity.HeatEffectEntity {
- Game game
- long heatDuration
- long startTime
- BufferedImage heatImage
- float alpha
- float scale
+ void move(long)
+ void draw(Graphics)
+ boolean isFinished()
- void loadHeatImage()
+ void collidedWith(Entity)
}


interface org.newdawn.spaceinvaders.gameplay.net.GameNetworkAdapter {
~ Mode getMode()
~ void sendInput(PlayerInput)
~ GameSnapshot pollLatestSnapshot()
~ void tick(long)
~ void shutdown()
~ void sendEvent(GameEvent)
~ List<GameEvent> drainEvents()
}

enum org.newdawn.spaceinvaders.gameplay.net.Mode {
+  SERVER
+  CLIENT
+  LOCAL
}

class org.newdawn.spaceinvaders.gameplay.entity.BossEntity {
- Game game
- boolean used
- int currentHP
- int maxHP
- double moveSpeed
- boolean movingRight
- long lastIceAttack
- long iceAttackInterval
- long lastIceBallAttack
- long iceBallAttackInterval
- long lastMagneticField
- long magneticFieldInterval
- long lastAttackTime
- long attackInterval
- int currentAttackPattern
- int[] attackPatterns
- boolean[] attackUsed
- long lastRound2Attack
- long round2AttackInterval
- int round2AttackPattern
- long lastRound3Attack
- long round3AttackInterval
- int round3AttackPattern
- long lastRound4HealAttack
- long round4HealInterval
- long lastRound4GreenSphereAttack
- long round4GreenSphereInterval
- long lastRound4PlayerLineAttack
- long round4PlayerLineInterval
- long round4StartTime
- long round4TimeLimit
- boolean round4TimerStarted
- int round
- int phase
- double fanAngle
- {static} String getBossSpriteForRound(int)
+ void move(long)
+ void takeDamage(int)
- void createBossExplosion()
+ void draw(Graphics)
+ void collidedWith(Entity)
+ int getCurrentHP()
+ int getMaxHP()
+ int getPhase()
+ java.awt.Rectangle getBounds()
+ void tryIceAttack()
+ void setIceAttackInterval(long)
+ void tryIceBallAttack()
- void performTripleIceBallAttack()
+ void setIceBallAttackInterval(long)
+ void tryMagneticFieldAttack()
+ void trySequentialRandomAttack()
- void executeAttackPattern(int)
+ void tryIceAttackNow()
+ void tryIceBallAttackNow()
+ void tryFanIceBallsAttackNow()
+ void tryWaveIceBallsAttackNow()
+ void trySpiralIceBallsAttackNow()
- void tryRound2LaserAttack()
- void executeRound2LaserAttack()
- void executeRound2PhaseAttack()
- void executeRound2RandomAttack()
- void executeRound2QuadAttack()
- void executeRound2MachineGunAttack()
- void tryRound3StraightAttack()
- void executeRound3StraightAttack()
- void executeRound3RandomAttack()
- void executeRound3PullAttack()
- void tryRound4HealAttack()
- void executeRound4HealAttack()
- void checkRound4Timer()
- void killPlayer()
- void tryRound4GreenSphereAttack()
- void executeRound4GreenSphereAttack()
- void tryRound4PlayerLineAttack()
- void executeRound4PlayerLineAttack()
+ void healToFull()
}


class org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round2Phase1Attack {
- Game game
- double moveSpeed
- int damage
- Image projectileImage
- double targetY
- boolean phase1Complete
+ void move(long)
- void createPhase2Attack()
+ void draw(Graphics)
+ void collidedWith(Entity)
+ int getDamage()
+ boolean isPhase1Complete()
}


class org.newdawn.spaceinvaders.gameplay.GameStateManager {
- boolean gameRunning
- boolean waitingForKeyPress
- String message
- int currentRound
- int MAX_ROUND
- int alienCount
- java.util.Map<String,PlayerState> players
- String localPlayerId
- boolean showingSkillMenu
- int selectedSkill
- boolean showingPauseMenu
- int selectedPauseMenuItem
- boolean showingRoundInfo
- long roundInfoStartTime
- boolean showingQuitConfirm
- int selectedQuitOption
- boolean gameCompleted
- long lastFire
- long lastAlienFire
- long alienFiringInterval
- long baseAlienFiringInterval
- long firingInterval
- long lastFpsTime
- int fps
- ArrayList<Entity> entities
- ArrayList<Entity> removeList
- boolean logicRequiredThisLoop
- boolean isRoundTransition
- int earnedCoins
- long gameStartTime
- long pausedTime
- long pauseStartTime
- PlayerState getLocalPlayerState()
+ void startNewGame()
+ void resetGame()
+ boolean isGameRunning()
+ void setGameRunning(boolean)
+ boolean isWaitingForKeyPress()
+ void setWaitingForKeyPress(boolean)
+ String getMessage()
+ void setMessage(String)
+ int getCurrentRound()
+ void setCurrentRound(int)
+ int getMaxRound()
+ int getAlienCount()
+ void setAlienCount(int)
+ int getAttackPower()
+ void setAttackPower(int)
+ double getAttackSpeed()
+ void setAttackSpeed(double)
+ int getMaxHP()
+ void setMaxHP(int)
+ int getCurrentHP()
+ void setCurrentHP(int)
+ int getSkillPoints()
+ void setSkillPoints(int)
+ java.util.Collection<PlayerState> getPlayerStates()
+ PlayerState getPlayerState(String)
+ PlayerState ensurePlayer(String)
+ String getLocalPlayerId()
+ void setLocalPlayerId(String)
+ long getLastFire()
+ void setLastFire(long)
+ long getLastAlienFire()
+ void setLastAlienFire(long)
+ long getAlienFiringInterval()
+ void setAlienFiringInterval(long)
+ long getBaseAlienFiringInterval()
+ long getFiringInterval()
+ long getLastFpsTime()
+ void setLastFpsTime(long)
+ int getFps()
+ void setFps(int)
+ ArrayList<Entity> getEntities()
+ ArrayList<Entity> getRemoveList()
+ boolean isLogicRequiredThisLoop()
+ void setLogicRequiredThisLoop(boolean)
+ boolean isRoundTransition()
+ void setRoundTransition(boolean)
+ void takeDamage()
+ boolean advanceRound()
+ void addSkillPoints(int)
+ boolean isShowingSkillMenu()
+ void showSkillMenu()
+ void hideSkillMenu()
+ int getSelectedSkill()
+ void setSelectedSkill(int)
+ boolean isShowingPauseMenu()
+ void showPauseMenu()
+ void hidePauseMenu()
+ int getSelectedPauseMenuItem()
+ void setSelectedPauseMenuItem(int)
+ int getEarnedCoins()
+ void setEarnedCoins(int)
+ void addEarnedCoins(int)
+ long getGameStartTime()
+ void setGameStartTime(long)
+ String getPlayTime()
+ long getPlayTimeMs()
+ boolean isShowingRoundInfo()
+ void showRoundInfo()
+ void hideRoundInfo()
+ String getRoundDescription(int)
+ boolean isShowingQuitConfirm()
+ void showQuitConfirm()
+ void hideQuitConfirm()
+ int getSelectedQuitOption()
+ void setSelectedQuitOption(int)
+ void startPause()
+ void endPause()
+ boolean isPaused()
+ boolean isGameCompleted()
+ void setGameCompleted(boolean)
+ boolean shouldAutoCloseRoundInfo()
}


class org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round4HealAttack {
- Game game
- java.awt.Image healImage
- long healDuration
- long startTime
- int healWidth
- int healHeight
- void loadHealImage()
+ void move(long)
- void healBossToFull()
+ void draw(Graphics)
+ void collidedWith(Entity)
}


class org.newdawn.spaceinvaders.gameplay.BackgroundRenderer {
- {static} int WIDTH
- {static} int HEIGHT
- BufferedImage cachedBackground
- String resourcePath
+ void setResourcePath(String)
+ void draw(Graphics2D)
- void ensureLoaded(Graphics2D)
}


class org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round2MachineGunAttack {
- Game game
- java.awt.Image attackImage
- int damage
- double moveSpeed
- double targetY
- long startTime
- void loadAttackImage()
+ void move(long)
+ void draw(Graphics)
+ void collidedWith(Entity)
}


class org.newdawn.spaceinvaders.gameplay.sprite.SpriteStore {
- {static} SpriteStore single
- HashMap<String,Sprite> sprites
+ {static} SpriteStore get()
+ Sprite getSprite(String)
- BufferedImage resizeImageForGameplay(BufferedImage,String)
- void fail(String)
}


class org.newdawn.spaceinvaders.gameplay.entity.CoinDisplayEntity {
- Game game
- BufferedImage coinImage
- int coinAmount
- long displayDuration
- long creationTime
- {static} double RISE_SPEED
- {static} long FADE_START
- void loadCoinImage()
+ void move(long)
+ void draw(Graphics)
+ void collidedWith(Entity)
+ int getCoinAmount()
+ void doLogic()
}


class org.newdawn.spaceinvaders.gameplay.core.SkillDropTable {
- {static} SkillDrop INVINCIBLE_DROP
- {static} SkillDrop TRIPLE_SHOT_DROP
- {static} SkillDrop MISSILE_DROP
+ {static} SkillDrop rollDrop(int)
}


class org.newdawn.spaceinvaders.gameplay.core.SkillDropTable$SkillDrop {
+ int skillType
+ int skillValue
}

class org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round2QuadAttack {
- Game game
- java.awt.Image attackImage
- int damage
- double moveSpeed
- int direction
- long attackDuration
- long startTime
- void loadAttackImage()
+ void move(long)
+ void draw(Graphics)
+ void collidedWith(Entity)
}


class org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round2Phase2Attack {
- Game game
- double moveSpeed
- int damage
- Image projectileImage
- double angle
+ void move(long)
+ void draw(Graphics)
+ void collidedWith(Entity)
+ int getDamage()
+ double getAngle()
}


abstract class org.newdawn.spaceinvaders.gameplay.entity.Entity {
- {static} java.util.concurrent.atomic.AtomicLong ID_GENERATOR
- long entityId
- String ownerId
# double x
# double y
# Sprite sprite
# double dx
# double dy
- Rectangle me
- Rectangle him
+ long getEntityId()
+ String getOwnerId()
+ void setOwnerId(String)
+ EntitySnapshot toSnapshot()
# String spriteRef()
+ void applySnapshot(EntitySnapshot)
+ void move(long)
+ void setHorizontalMovement(double)
+ void setVerticalMovement(double)
+ double getHorizontalMovement()
+ double getVerticalMovement()
+ void draw(Graphics)
+ void doLogic()
+ int getX()
+ int getY()
+ boolean collidesWith(Entity)
+ Rectangle getBounds()
+ void changeSkin(String)
+ {abstract}void collidedWith(Entity)
+ double getDX()
+ double getDY()
+ void setDX(double)
+ void setDY(double)
}


class org.newdawn.spaceinvaders.gameplay.entity.AlienEntity {
- double moveSpeed
- Game game
- Sprite[] frames
- long lastFrameChange
- long frameDuration
- int frameNumber
+ long lastFire
+ long firingInterval
- int currentHP
- int maxHP
- boolean movingRight
- boolean movingDown
- long lastDirectionChange
- long directionChangeInterval
- long lastCollisionTime
- {static} long COLLISION_COOLDOWN
- {static} String getAlienSpriteForRound(int)
+ void move(long)
+ void doLogic()
+ void tryToFire()
+ void takeDamage(int)
+ int getCurrentHP()
+ int getMaxHP()
- void changeDirection()
- void changeVerticalDirection()
+ void collideWithAlien()
- boolean isBossRound()
- void handleAlienCollision(Entity)
- void avoidPlayer()
+ void draw(Graphics)
+ Rectangle getBounds()
+ void collidedWith(Entity)
}


class org.newdawn.spaceinvaders.gameplay.entity.ShotEntity {
- double moveSpeed
- Game game
- boolean used
- boolean isAlienShot
- boolean isSkillDrop
- int skillType
- int skillValue
- boolean hasPiercing
- boolean isNearMonsterShot
+ void move(long)
- BufferedImage loadSkillImageForDrop(int)
+ void collidedWith(Entity)
+ void draw(Graphics)
+ boolean hasPiercing()
+ void setPiercing(boolean)
+ boolean isAlienShot()
+ boolean isSkillDrop()
+ int getSkillType()
+ int getSkillValue()
+ void setNearMonsterShot(boolean)
+ java.awt.Rectangle getBounds()
}


class org.newdawn.spaceinvaders.gameplay.PlayerState {
- String playerId
- int attackPower
- double attackSpeed
- int maxHP
- int currentHP
- int skillPoints
+ String getPlayerId()
+ int getAttackPower()
+ void setAttackPower(int)
+ double getAttackSpeed()
+ void setAttackSpeed(double)
+ int getMaxHP()
+ void setMaxHP(int)
+ int getCurrentHP()
+ void setCurrentHP(int)
+ int getSkillPoints()
+ void setSkillPoints(int)
+ void addSkillPoints(int)
+ void resetForNewGame()
+ void takeDamage(int)
+ boolean isDead()
}


class org.newdawn.spaceinvaders.gameplay.entity.ExplosionEntity {
- Game game
- long explosionDuration
- long startTime
- double maxRadius
- double currentRadius
- boolean damageDealt
- long lastDamageTime
- long damageInterval
- java.util.Set<Entity> damagedEntities
- BufferedImage explosionImage
+ void move(long)
+ void draw(Graphics)
+ double getCurrentRadius()
+ double getMaxRadius()
+ boolean isFinished()
- void loadExplosionImage()
- void dealDamageToEnemies()
+ void collidedWith(Entity)
}


class org.newdawn.spaceinvaders.gameplay.UIRenderer {
- {static} Font KOSTAR_FONT
- {static} BasicStroke STROKE_2PX
- SharedHudRenderer sharedHudRenderer
- {static} void loadKostarFont()
+ {static} Font getKostarFont(int)
+ {static} Font getKostarFont(int,int)
+ void drawGameUI(Graphics2D,GameStateManager,SkillManager)
+ void drawMessage(Graphics2D,String)
- void drawGameOverMessage(Graphics2D,String)
- void drawGameClearMessage(Graphics2D,String)
+ void updateFPSDisplay(String,int)
+ void drawPauseOverlay(Graphics2D,int)
+ void drawSkillOverlay(Graphics2D,int,int,double,int,int,int,int,int,SkillManager)
- void drawMenuButton(Graphics2D,String,int,int,int,int,boolean)
- void drawCard(Graphics2D,int,int,int,int,String,String,boolean)
- void drawUpgradeStats(Graphics2D,GameStateManager)
+ void drawRoundInfoOverlay(Graphics2D,GameStateManager)
+ void drawQuitConfirmOverlay(Graphics2D,GameStateManager)
- void drawConfirmButton(Graphics2D,String,int,int,int,int,boolean)
}


class org.newdawn.spaceinvaders.gameplay.UIRenderer$SinglePlayerHudContext {
- GameStateManager gameStateManager
- SkillManager skillManager
+ int getCurrentRound()
+ int getMaxRound()
+ int getCurrentHp()
+ int getMaxHp()
+ int getSkillPoints()
+ int getAttackPower()
+ double getAttackSpeed()
+ int getInvincibleSkillCount()
+ int getTripleShotSkillCount()
+ int getMissileSkillCount()
+ boolean isInvincibleActive()
+ long getInvincibleRemainingMs()
+ boolean isTripleShotActive()
+ long getTripleShotRemainingMs()
+ String getFormattedPlayTime()
+ int getEarnedCoins()
}


class org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round3StraightAttack {
- Game game
- java.awt.Image attackImage
- int damage
- double moveSpeed
- long attackDuration
- long startTime
- int attackWidth
- int attackHeight
- void loadAttackImage()
+ void move(long)
+ void draw(Graphics)
+ void collidedWith(Entity)
}


class org.newdawn.spaceinvaders.gameplay.net.GameSnapshot {
+ long serverTime
+ int round
+ List<EntitySnapshot> entities
+ Map<String,PlayerScalarState> players
}

class org.newdawn.spaceinvaders.gameplay.net.GameSnapshot$PlayerScalarState {
+ int hp
+ int maxHp
+ int atk
+ double aspd
+ int skillPts
}

class org.newdawn.spaceinvaders.gameplay.core.SharedGameplayCoordinator {
- GameplayContext context
+ GameStateManager getGameStateManager()
+ void startNewGame(String)
+ void initializeRound(String)
+ void handleAlienKilled(String)
+ void handleNearMonstersCleared(String)
+ void handleRoundClear(String)
+ boolean isNearRound(int)
+ int getBossRoundFromNearRound(int)
- int mapBossRound(int)
- void spawnNearMonsters(int)
- void spawnBoss(int)
- void resetEntities()
- void notifyGameCompleted(GameStateManager)
}


class org.newdawn.spaceinvaders.gameplay.entity.MissileEntity {
- Game game
- double targetX
- double targetY
- double speed
- boolean used
+ void move(long)
+ void draw(Graphics)
+ void collidedWith(Entity)
}


class org.newdawn.spaceinvaders.gameplay.entity.entity_attack.IceBallAttack {
- Game game
- double moveSpeed
- int damage
- Image iceBallImage
- double scale
- double dirX
- double dirY
- void loadIceBallImage()
+ void move(long)
+ void draw(Graphics)
+ Rectangle getBounds()
+ void collidedWith(Entity)
}


class org.newdawn.spaceinvaders.gameplay.SkillManager {
- int attackPowerLevel
- int attackSpeedLevel
- int hpUpLevel
- int baseAttackPowerCost
- int baseAttackSpeedCost
- int baseHpUpCost
- boolean isInvincible
- long invincibleEndTime
- boolean hasTripleShot
- long tripleShotEndTime
- int invincibleSkills
- int tripleShotSkills
- int missileSkills
- GameplayContext context
+ void reset()
+ void updateSkillEffects()
+ void addSkillToInventory(int,int)
+ void activateSkill(int,int)
+ void extendSkill(int,int)
+ void dropSkill(int)
- void addSkillDrop(int,int,int,int)
+ int getRandomSkillPoints(int)
+ double getSkillDropChance(int)
+ int getAttackPowerCost()
+ int getAttackSpeedCost()
+ int getHpUpCost()
+ void increaseAttackPowerLevel()
+ void increaseAttackSpeedLevel()
+ void increaseHpUpLevel()
+ int getAttackPowerLevel()
+ int getAttackSpeedLevel()
+ int getHpUpLevel()
+ boolean isInvincible()
+ void setInvincible(boolean)
+ long getInvincibleEndTime()
+ void setInvincibleEndTime(long)
+ boolean hasTripleShot()
+ void setHasTripleShot(boolean)
+ long getTripleShotEndTime()
+ void setTripleShotEndTime(long)
+ int getInvincibleSkills()
+ void setInvincibleSkills(int)
+ int getTripleShotSkills()
+ void setTripleShotSkills(int)
+ int getMissileSkills()
+ void setMissileSkills(int)
+ long getRemainingTime(long)
- void fireMissileAtRandomTarget()
}


class org.newdawn.spaceinvaders.gameplay.Game {
- ShipEntity ship
- double moveSpeed
- UserManager userManager
- ResolutionManager resolutionManager
- String currentSpaceshipSkin
- String currentWeaponSkin
- boolean wasPaused
- GameStateManager gameStateManager
- InputManager inputManager
- SkillManager skillManager
- UIRenderer uiRenderer
- BackgroundRenderer backgroundRenderer
- SharedGameplayCoordinator gameplayCoordinator
- boolean requestMainMenu
- ScreenNavigator navigator
- long gameStartTime
- GameNetworkAdapter networkAdapter
+ void setResolutionManager(ResolutionManager)
+ void startGame()
- void initEntities()
+ void updateLogic()
+ void removeEntity(Entity)
+ void notifyDeath()
+ void notifyPlayerDamaged(int)
+ void notifyWin()
+ void notifyAlienKilled()
+ void tryToFire()
+ void addAlienShot(int,int)
+ void addAimedAlienShot(int,int,int)
+ void createSkillDrop(int,int,int,int)
- void tryAlienFire()
+ int getPlayerAttackPower()
+ int getCurrentRound()
+ boolean isPlayerInvincible()
+ boolean hasPiercingShots()
+ boolean hasTripleShot()
+ void addSkillToInventory(int,int)
+ void fireMissile(String,double,double)
+ void fireMissile(double,double)
+ void addEntity(Entity)
+ void createCoinDrop(int,int,int)
+ void addEarnedCoins(int)
+ void showCoinEarned(int,int,int)
+ SkillManager getSkillManager(String)
+ ShipEntity getShip(String)
+ ShipEntity createPlayerShip(String)
+ Entity createAlienEntity(int,int)
+ Entity createNearEntity(int,int)
+ Entity createBossEntity(int)
+ List<Entity> getActiveEntities()
+ List<Entity> getPendingRemovals()
+ void onRoundBackgroundChanged(int)
+ void addEarnedCoins(String,int)
+ void showCoinEarned(String,int,int,int)
+ void onGameCompleted(String)
+ void saveCoinsAndPlayTime()
- void saveGameRecordToDB(org.newdawn.spaceinvaders.database.GameRecord)
- void saveSingleLeaderboardEntry(long,String)
+ void update(long)
+ void render(Graphics2D)
+ Entity getShip()
+ int getShipX()
+ int getShipY()
+ double getMoveSpeed()
+ boolean isWaitingForKeyPress()
+ void returnToMainMenu()
+ void setWaitingForKeyPress(boolean)
+ void startNewGame()
+ ArrayList<Entity> getEntities()
+ GameStateManager getGameplayState()
+ SkillManager getSkillManager()
+ UIRenderer getUIRenderer()
+ void drawSkillMenu(java.awt.Graphics2D)
+ void drawPauseMenu(java.awt.Graphics2D)
+ void drawRoundInfoOverlay(java.awt.Graphics2D,GameStateManager)
+ void drawQuitConfirmOverlay(java.awt.Graphics2D,GameStateManager)
+ void createExplosion(int,int,double)
+ void createHeatEffect(int,int,double)
+ void addScore(int)
+ void addSkillPoints(int)
+ void dropRandomSkill(int,int)
+ void dropRandomSkillPoints(int,int)
+ boolean hasBoss()
+ BossEntity getBoss()
+ void notifyBossDefeated()
+ void checkAllNearMonstersDefeated()
+ void addBossShot(int,int)
+ void setUserManager(UserManager)
+ UserManager getUserManager()
+ GameStateManager getGameStateManager()
- void applyEquippedItems()
- void applySpaceshipSkin()
- String mapItemIdToSkinFile(String)
- void applyWeaponSkin()
- void applyPowerupEffects()
+ String getCurrentSpaceshipSkin()
+ String getCurrentWeaponSkin()
+ void goToMainMenu()
+ boolean isRequestingMainMenu()
+ void resetMainMenuRequest()
+ void updateBackgroundForRound(int)
+ boolean canEnemiesAttack()
+ ShipEntity getPlayerShip()
+ {static} void main(String[])
}


class org.newdawn.spaceinvaders.gameplay.entity.NearEntity {
- Game game
- java.awt.Image nearImage
- int currentHP
- int maxHP
- double moveSpeed
- boolean movingRight
- int round
- int nearWidth
- int nearHeight
- long lastShot
- long shotInterval
- int monsterId
- {static} String getNearSpriteForRound(int)
- {static} int getBossRoundFromNearRound(int)
- void loadNearImage()
+ void move(long)
- void checkNearMonsterCollision()
- void tryShoot()
+ void takeDamage(int)
+ void draw(Graphics)
+ void collidedWith(Entity)
+ int getCurrentHP()
+ int getMaxHP()
+ int getRound()
+ java.awt.Rectangle getBounds()
- String getShotSpriteForRound(int)
}


class org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round3RandomAttack {
- Game game
- java.awt.Image attackImage
- int damage
- int moveSpeed
- long attackDuration
- long startTime
- int attackWidth
- int attackHeight
- long damageDelay
- boolean damageApplied
- void loadAttackImage()
+ void move(long)
+ void draw(Graphics)
+ void collidedWith(Entity)
}


class org.newdawn.spaceinvaders.gameplay.entity.BossShotEntity {
- Game game
- boolean used
- double directionX
- double directionY
- double speed
- int radius
- boolean canSplit
- double splitY
- int splitCount
- boolean hasSplit
+ void move(long)
- void split()
+ void draw(Graphics)
+ void collidedWith(Entity)
+ double getDirectionX()
+ double getDirectionY()
+ double getSpeed()
+ boolean isUsed()
}


class org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round3BlackHoleAttack {
- Game game
- java.awt.Image attackImage
- int damage
- int moveSpeed
- long attackDuration
- long startTime
- int attackWidth
- int attackHeight
- double targetX
- double targetY
- void loadAttackImage()
+ void move(long)
+ void draw(Graphics)
+ void collidedWith(Entity)
}


class org.newdawn.spaceinvaders.gameplay.sprite.Sprite {
- Image image
+ int getWidth()
+ int getHeight()
+ Image getImage()
+ void draw(Graphics,int,int)
+ void draw(Graphics,int,int,int,int)
}


class org.newdawn.spaceinvaders.gameplay.entity.EntitySnapshot {
+ long id
+ String ownerId
+ String sprite
+ double x
+ double y
+ double dx
+ double dy
+ int w
+ int h
}

class org.newdawn.spaceinvaders.gameplay.entity.CoinEntity {
- Game game
- BufferedImage coinImage
- int coinValue
- {static} int COIN_SIZE
- {static} double FALL_SPEED
- void loadCoinImage()
+ void move(long)
+ void draw(Graphics2D)
+ void collidedWith(Entity)
+ int getCoinValue()
+ void doLogic()
}


class org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round2LaserAttack {
- Game game
- double moveSpeed
- int damage
- Image laserImage
- double rotationAngle
- double laserLength
- double laserWidth
- long startTime
+ void move(long)
+ void draw(Graphics)
+ void collidedWith(Entity)
+ int getDamage()
+ void setDamage(int)
}


class org.newdawn.spaceinvaders.gameplay.net.LocalLoopbackNetworkAdapter {
- GameStateManager gsm
- Queue<PlayerInput> inputs
- GameSnapshot latest
- Queue<GameEvent> events
+ Mode getMode()
+ void sendInput(PlayerInput)
+ GameSnapshot pollLatestSnapshot()
+ void tick(long)
+ void shutdown()
+ void sendEvent(GameEvent)
+ List<GameEvent> drainEvents()
}


class org.newdawn.spaceinvaders.gameplay.entity.ShipEntity {
- Game game
+ void move(long)
- void applyMagneticFieldEffects()
+ void draw(Graphics)
+ void pullTowards(double,double)
+ void collidedWith(Entity)
}


class org.newdawn.spaceinvaders.gameplay.InputManager {
- GameStateManager gameStateManager
- Game game
- SkillManager skillManager
- boolean leftPressed
- boolean rightPressed
- boolean firePressed
+ void updateGameplayInput()
+ void reset()
- void handlePauseMenuInput(KeyEvent)
- void handlePauseMenuSelection()
- void handleSkillMenuInput(KeyEvent)
- void handleSkillSelection()
- void handleQuitConfirmInput(KeyEvent)
- void handleQuitConfirmSelection()
+ boolean isLeftPressed()
+ boolean isRightPressed()
+ boolean isFirePressed()
}


class org.newdawn.spaceinvaders.gameplay.InputManager$KeyInputHandler {
+ void keyPressed(KeyEvent)
+ void keyReleased(KeyEvent)
+ void keyTyped(KeyEvent)
- void handleGameplayKeyPressed(KeyEvent)
- void handleGameplayKeyReleased(KeyEvent)
}

class org.newdawn.spaceinvaders.gameplay.InputManager$MouseInputHandler {
+ void mouseClicked(MouseEvent)
}



org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.SideMonster
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.Skill
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round4GreenSphereAttack
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round4PlayerLineAttack
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round2RandomAttack
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.entity_attack.IceAttack
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round3PullAttack
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.entity_attack.MagneticFieldEntity
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.HeatEffectEntity
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.BossEntity
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round2Phase1Attack
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round4HealAttack
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round2MachineGunAttack
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.CoinDisplayEntity
org.newdawn.spaceinvaders.gameplay.core.SkillDropTable +.. org.newdawn.spaceinvaders.gameplay.core.SkillDropTable$SkillDrop
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round2QuadAttack
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round2Phase2Attack
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.AlienEntity
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.ShotEntity
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.ExplosionEntity
org.newdawn.spaceinvaders.gameplay.UIRenderer +.. org.newdawn.spaceinvaders.gameplay.UIRenderer$SinglePlayerHudContext
org.newdawn.spaceinvaders.gameplay.HudContext <|.. org.newdawn.spaceinvaders.gameplay.UIRenderer$SinglePlayerHudContext
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round3StraightAttack
org.newdawn.spaceinvaders.gameplay.net.GameSnapshot +.. org.newdawn.spaceinvaders.gameplay.net.GameSnapshot$PlayerScalarState
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.MissileEntity
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.entity_attack.IceBallAttack
org.newdawn.spaceinvaders.app.Screen <|.. org.newdawn.spaceinvaders.gameplay.Game
org.newdawn.spaceinvaders.gameplay.core.GameplayContext <|.. org.newdawn.spaceinvaders.gameplay.Game
java.awt.Canvas <|-- org.newdawn.spaceinvaders.gameplay.Game
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.NearEntity
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round3RandomAttack
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.BossShotEntity
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round3BlackHoleAttack
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.CoinEntity
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.entity_attack.Round2LaserAttack
org.newdawn.spaceinvaders.gameplay.net.GameNetworkAdapter <|.. org.newdawn.spaceinvaders.gameplay.net.LocalLoopbackNetworkAdapter
org.newdawn.spaceinvaders.gameplay.entity.Entity <|-- org.newdawn.spaceinvaders.gameplay.entity.ShipEntity
org.newdawn.spaceinvaders.gameplay.InputManager +.. org.newdawn.spaceinvaders.gameplay.InputManager$KeyInputHandler
org.newdawn.spaceinvaders.gameplay.KeyAdapter <|-- org.newdawn.spaceinvaders.gameplay.InputManager$KeyInputHandler
org.newdawn.spaceinvaders.gameplay.InputManager +.. org.newdawn.spaceinvaders.gameplay.InputManager$MouseInputHandler
org.newdawn.spaceinvaders.gameplay.MouseAdapter <|-- org.newdawn.spaceinvaders.gameplay.InputManager$MouseInputHandler
@enduml