package org.newdawn.spaceinvaders.multyplay.entity;

import java.awt.*;import org.newdawn.spaceinvaders.multyplay.core.MultiGameRuntime;

public class BossShotEntity extends Entity {
    private MultiGameRuntime game; private boolean used=false; private double directionX; private double directionY; private double speed; private int radius; private boolean canSplit; private double splitY; private int splitCount; private boolean hasSplit=false;
    public BossShotEntity(MultiGameRuntime game,int x,int y,double dirX,double dirY,double speed){ super("sprites/shot.gif",x,y); this.game=game; this.directionX=dirX; this.directionY=dirY; this.speed=speed; this.radius=8; this.canSplit=false; dx=dirX*speed; dy=dirY*speed; }
    public BossShotEntity(MultiGameRuntime game,int x,int y,double dirX,double dirY,double speed,int radius,boolean canSplit,double splitY,int splitCount){ super("sprites/shot.gif",x,y); this.game=game; this.directionX=dirX; this.directionY=dirY; this.speed=speed; this.radius=radius; this.canSplit=canSplit; this.splitY=splitY; this.splitCount=splitCount; dx=dirX*speed; dy=dirY*speed; }
    public void move(long delta){ super.move(delta); if(canSplit && !hasSplit && y>=splitY){ split(); hasSplit=true; game.removeEntity(this); return; } if(y>750||y<-100||x<-100||x>900) game.removeEntity(this); }
    private void split(){ for(int i=0;i<splitCount;i++){ double a=2*Math.PI*i/splitCount; double ndx=Math.cos(a); double ndy=Math.sin(a); BossShotEntity small=new BossShotEntity(game,(int)x,(int)y,ndx,ndy,speed*0.8); small.radius=Math.max(4,radius/2); game.addEntity(small); } }
    public void draw(Graphics g){ Graphics2D g2d=(Graphics2D)g; int centerX=(int)x + (sprite!=null? sprite.getWidth()/2:0); int centerY=(int)y + (sprite!=null? sprite.getHeight()/2:0); int glowAlpha=canSplit?100:60; int coreAlpha=canSplit?240:220; g2d.setColor(new Color(255,100,100,glowAlpha)); g2d.fillOval(centerX-radius-3,centerY-radius-3,(radius+3)*2,(radius+3)*2); g2d.setColor(new Color(255,50,50,coreAlpha)); g2d.fillOval(centerX-radius,centerY-radius,radius*2,radius*2); if(radius>4){ g2d.setColor(new Color(255,200,200,180)); g2d.fillOval(centerX-radius+2,centerY-radius+2,(radius-2)*2,(radius-2)*2);} if(radius>6){ g2d.setColor(new Color(255,255,255,200)); g2d.fillOval(centerX-radius+4,centerY-radius+4,(radius-4)*2,(radius-4)*2);} if(speed>0 && radius>4){ int dist=Math.max(8,radius); int tx=centerX-(int)(directionX*dist); int ty=centerY-(int)(directionY*dist); g2d.setColor(new Color(255,100,100,80)); int tr=Math.max(3,radius-1); g2d.fillOval(tx-tr,ty-tr,tr*2,tr*2); tx=centerX-(int)(directionX*dist*1.5); ty=centerY-(int)(directionY*dist*1.5); g2d.setColor(new Color(255,100,100,40)); tr=Math.max(2,radius-2); g2d.fillOval(tx-tr,ty-tr,tr*2,tr*2);} }
    public void collidedWith(Entity other){ if(used) return; if(other instanceof ShipEntity){ game.removeEntity(this); game.notifyDeath(); used=true; } }
    public double getDirectionX(){ return directionX; } public double getDirectionY(){ return directionY; } public double getSpeed(){ return speed; } public boolean isUsed(){ return used; }
}
