package org.newdawn.spaceinvaders.multyplay.entity;

import java.awt.*;import java.awt.image.BufferedImage;import javax.imageio.ImageIO;import java.io.InputStream;
import org.newdawn.spaceinvaders.multyplay.core.MultiGameRuntime;

public class ShotEntity extends Entity {
    private double moveSpeed = -300; private MultiGameRuntime game; private boolean used = false; private boolean isAlienShot = false; private boolean isSkillDrop = false; private int skillType = -1; private int skillValue = 0; private boolean hasPiercing = false;
    public ShotEntity(MultiGameRuntime game,String sprite,int x,int y){ super(sprite,x,y); this.game=game; dy=moveSpeed; }
    public ShotEntity(MultiGameRuntime game,String sprite,int x,int y,boolean isAlienShot){ super(sprite,x,y); this.game=game; this.isAlienShot=isAlienShot; dy=isAlienShot?300:moveSpeed; }
    public ShotEntity(MultiGameRuntime game,String sprite,int x,int y,boolean isAlienShot,boolean hasPiercing){ super(sprite,x,y); this.game=game; this.isAlienShot=isAlienShot; this.hasPiercing=hasPiercing; dy=isAlienShot?300:moveSpeed; }
    public ShotEntity(MultiGameRuntime game,String sprite,int x,int y,boolean isAlienShot,int skillType,int skillValue){ super(sprite,x,y); this.game=game; this.isAlienShot=isAlienShot; this.skillType=skillType; this.skillValue=skillValue; if(skillType>=0){ isSkillDrop=true; dx=0; dy=150; } else dy=isAlienShot?300:moveSpeed; }
    public void move(long delta){ super.move(delta); if(isSkillDrop){ if(y>700) game.removeEntity(this); } else if(isAlienShot){ if(y>700) game.removeEntity(this); } else { if(y<-100) game.removeEntity(this); } }
    public void draw(Graphics g){ if(isSkillDrop){ Graphics2D g2d=(Graphics2D)g; BufferedImage img=loadSkillImage(skillType); if(img!=null){ int s=32; int dx=(int)x - s/2; int dy=(int)y - s/2; g2d.drawImage(img,dx,dy,s,s,null);} else { g.setColor(Color.BLACK); g.fillRect((int)x-16,(int)y-16,32,32); g.setColor(Color.GRAY); g.drawRect((int)x-16,(int)y-16,32,32); g.setColor(Color.WHITE); g.drawString("S"+skillType,(int)x-8,(int)y+4);} g.setColor(new Color(255,255,255,50)); g.fillOval((int)x-18,(int)y-18,36,36);} else if(isAlienShot){ Graphics2D g2d=(Graphics2D)g; int centerX=(int)x + (sprite!=null ? sprite.getWidth()/2:0); int centerY=(int)y + (sprite!=null ? sprite.getHeight()/2:0); int r=8; g2d.setColor(new Color(255,100,100,60)); g2d.fillOval(centerX-r-3,centerY-r-3,(r+3)*2,(r+3)*2); g2d.setColor(new Color(255,50,50,220)); g2d.fillOval(centerX-r,centerY-r,r*2,r*2); g2d.setColor(new Color(255,200,200,180)); g2d.fillOval(centerX-r+2,centerY-r+2,(r-2)*2,(r-2)*2); g2d.setColor(new Color(255,255,255,200)); g2d.fillOval(centerX-r+4,centerY-r+4,(r-4)*2,(r-4)*2); g2d.setColor(new Color(255,100,100,80)); g2d.fillOval(centerX-r+1,centerY-r+6,(r-1)*2,(r-1)*2); g2d.setColor(new Color(255,100,100,40)); g2d.fillOval(centerX-r+2,centerY-r+10,(r-2)*2,(r-2)*2);} else { super.draw(g);} }
    public void collidedWith(Entity other){ if(used) return; if(isSkillDrop){ if(other instanceof ShipEntity){ game.removeEntity(this); game.addSkillToInventory(skillType,skillValue); used=true; } } else if(isAlienShot){ if(other instanceof ShipEntity){ game.removeEntity(this); game.notifyDeath(); used=true; } } else { if(other instanceof AlienEntity){ AlienEntity alien=(AlienEntity)other; alien.takeDamage(game.getPlayerAttackPower()); HeatEffectEntity heat=new HeatEffectEntity(game,(int)x,(int)y); game.addEntity(heat); if(!hasPiercing && !game.hasPiercingShots()){ game.removeEntity(this); used=true; } } else if(other instanceof BossEntity){ BossEntity boss=(BossEntity)other; boss.takeDamage(game.getPlayerAttackPower()); HeatEffectEntity heat=new HeatEffectEntity(game,(int)x,(int)y); game.addEntity(heat); game.removeEntity(this); used=true; } } }
    private BufferedImage loadSkillImage(int type){ String path; switch(type){ case 0: path="sprites/Skill/1.png"; break; case 1: path="sprites/Skill/2.png"; break; case 2: path="sprites/Skill/3.png"; break; case 3: path="sprites/Skill/4.png"; break; default: path="sprites/Skill/1.png"; } try(InputStream is=getClass().getClassLoader().getResourceAsStream(path)){ if(is!=null) return ImageIO.read(is); } catch(Exception e){ System.err.println("Failed skill image: "+path); } return null; }
    public boolean isAlienShot(){ return isAlienShot; }
}
